In [11]:
df = pd.read_csv('student_performance (1).csv')

In [6]:
df=pd.read_csv('student_performance (1).csv')

In [13]:
print("Dataset loaded sucessfully")

Dataset loaded sucessfully

In [7]:
df.head()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023

In [ ]:
df.tail()

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023

tail-helps in getting total,finding duplicates,

In [ ]:
print("No.of.R&C:",df.shape)

No.of.R&C: (30, 13)

In [ ]:
print("Columns in the dataset:")
print("Columns Names:",df.columns.tolist(1))

Columns in the dataset:
Columns Names: ['student_id', 'name', 'age', 'gender', 'department', 'semester', 'math_score', 'science_score', 'english_score', 'programming_score', 'attendance_percentage', 'city', 'admission_year']

tolist for colns will not come with any augument like 1,0

In [ ]:
print(df.dtypes)

student_id                int64
name                     object
age                       int64
gender                   object
department               object
semester                  int64
math_score                int64
science_score             int64
english_score             int64
programming_score         int64
attendance_percentage     int64
city                     object
admission_year            int64
dtype: object

In [ ]:
print(df.describe)

<bound method NDFrame.describe of     student_id            name  age  gender        department  semester  \
0         1001    Aarav Sharma   19    Male  Computer Science         2
1         1002     Priya Patel   20  Female  Computer Science         2
2         1003     Rohit Verma   19    Male       Electronics         2
3         1004     Sneha Reddy   20  Female        Mechanical         2
4         1005      Arjun Nair   19    Male  Computer Science         2
5         1006     Meera Joshi   20  Female       Electronics         2
6         1007     Kiran Kumar   21    Male             Civil         2
7         1008     Divya Singh   19  Female  Computer Science         2
8         1009    Rahul Mishra   20    Male        Mechanical         2
9         1010      Ananya Das   19  Female  Computer Science         2
10        1011     Vikram Iyer   20    Male       Electronics         2
11        1012     Pooja Gupta   19  Female             Civil         2
12        1013      Suresh Rao   21    Male  Computer Science         2
13        1014   Kavya Nambiar   20  Female        Mechanical         2
14        1015     Ajay Tiwari   19    Male  Computer Science         2
15        1016    Ritu Agarwal   20  Female       Electronics         2
16        1017    Manoj Pandey   21    Male             Civil         2
17        1018  Swati Kulkarni   19  Female  Computer Science         2
18        1019  Deepak Chauhan   20    Male        Mechanical         2
19        1020    Nisha Kapoor   19  Female  Computer Science         2
20        1021   Harish Pillai   20    Male       Electronics         2
21        1022     Tanvi Mehta   19  Female  Computer Science         2
22        1023    Sanjay Dubey   21    Male             Civil         2
23        1024   Preeti Saxena   20  Female        Mechanical         2
24        1025       Amit Bose   19    Male  Computer Science         2
25        1026      Rekha Nair   20  Female       Electronics         2
26        1027   Gaurav Shukla   21    Male  Computer Science         2
27        1028   Sunita Pillai   19  Female             Civil         2
28        1029      Nitin Jain   20    Male        Mechanical         2
29        1030  Akanksha Yadav   19  Female  Computer Science         2

    math_score  science_score  english_score  programming_score  \
0           85             78             72                 91
1           76             82             88                 79
2           65             74             61                 55
3           70             80             75                 48
4           92             88             81                 95
5           58             66             70                 52
6           73             69             65                 40
7           88             91             84                 93
8           62             71             58                 45
9           95             89             90                 97
10          80             75             68                 72
11          67             72             79                 44
12          83             86             77                 88
13          74             78             82                 51
14          71             69             64                 76
15          87             83             86                 69
16          56             61             55                 38
17          90             87             85                 92
18          68             73             62                 49
19          79             84             81                 83
20          64             70             67                 58
21          93             90             88                 96
22          61             66             59                 42
23          77             81             76                 53
24          86             82             79                 89
25          72             77             73                 63
26          84             79             75                 87
27          60             65             68                 39
28          75             76             70                 50
29          91             93             87                 94

    attendance_percentage                city  admission_year
0                      92              Mumbai            2023
1                      87           Ahmedabad            2023
2                      78               Delhi            2023
3                      95           Hyderabad            2023
4                      90               Kochi            2023
5                      72                Pune            2023
6                      85           Bangalore            2023
7                      96             Lucknow            2023
8                      68            Varanasi            2023
9                      98             Kolkata            2023
10                     83             Chennai            2023
11                     80              Jaipur            2023
12                     88              Mysore            2023
13                     91            Thrissur            2023
14                     75              Bhopal            2023
15                     93                Agra            2023
16                     65               Patna            2023
17                     94              Nagpur            2023
18                     77            Dehradun            2023
19                     89          Chandigarh            2023
20                     74  Thiruvananthapuram            2023
21                     97               Surat            2023
22                     70           Allahabad            2023
23                     86              Kanpur            2023
24                     91             Kolkata            2023
25                     82               Kochi            2023
26                     87             Lucknow            2023
27                     73  Thiruvananthapuram            2023
28                     84              Indore            2023
29                     95                Agra            2023  >

object-string

In [ ]:
print(df.isnull().sum())

student_id               0
name                     0
age                      0
gender                   0
department               0
semester                 0
math_score               0
science_score            0
english_score            0
programming_score        0
attendance_percentage    0
city                     0
admission_year           0
dtype: int64

missing val-is null-t/f, finalcount-sum()

In [ ]:
print("Student Name:")
print(df['name'])

Student Name:
0       Aarav Sharma
1        Priya Patel
2        Rohit Verma
3        Sneha Reddy
4         Arjun Nair
5        Meera Joshi
6        Kiran Kumar
7        Divya Singh
8       Rahul Mishra
9         Ananya Das
10       Vikram Iyer
11       Pooja Gupta
12        Suresh Rao
13     Kavya Nambiar
14       Ajay Tiwari
15      Ritu Agarwal
16      Manoj Pandey
17    Swati Kulkarni
18    Deepak Chauhan
19      Nisha Kapoor
20     Harish Pillai
21       Tanvi Mehta
22      Sanjay Dubey
23     Preeti Saxena
24         Amit Bose
25        Rekha Nair
26     Gaurav Shukla
27     Sunita Pillai
28        Nitin Jain
29    Akanksha Yadav
Name: name, dtype: object

In [ ]:
print("Student Age:")
print(df['age'])

Student Age:
0     19
1     20
2     19
3     20
4     19
5     20
6     21
7     19
8     20
9     19
10    20
11    19
12    21
13    20
14    19
15    20
16    21
17    19
18    20
19    19
20    20
21    19
22    21
23    20
24    19
25    20
26    21
27    19
28    20
29    19
Name: age, dtype: int64

In [ ]:
print("Student Gender:")
print(df['gender'])

Student Gender:
0       Male
1     Female
2       Male
3     Female
4       Male
5     Female
6       Male
7     Female
8       Male
9     Female
10      Male
11    Female
12      Male
13    Female
14      Male
15    Female
16      Male
17    Female
18      Male
19    Female
20      Male
21    Female
22      Male
23    Female
24      Male
25    Female
26      Male
27    Female
28      Male
29    Female
Name: gender, dtype: object

In [ ]:
print("Department in the dataset:")
print(df['department'].unique())

Department in the dataset:
['Computer Science' 'Electronics' 'Mechanical' 'Civil']

In [ ]:
print("Department Value Counts:")
print(df['department'].value_counts())

Department Value Counts:
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64

In [ ]:
cs_students=df[df['department']=='Computer Science']
print('number of cs students',len(cs_students))
print("Marks scored by Computer Science students:")
print(cs_students[['math_score', 'science_score', 'english_score', 'programming_score']])

number of cs students 13
Marks scored by Computer Science students:
    math_score  science_score  english_score  programming_score
0           85             78             72                 91
1           76             82             88                 79
4           92             88             81                 95
7           88             91             84                 93
9           95             89             90                 97
12          83             86             77                 88
14          71             69             64                 76
17          90             87             85                 92
19          79             84             81                 83
21          93             90             88                 96
24          86             82             79                 89
26          84             79             75                 87
29          91             93             87                 94

In [ ]:
high_attendance_students = df[df['attendance_percentage'] > 90]
print("Students with attendance percentage greater than 90:")
print(high_attendance_students[['name', 'department', 'attendance_percentage']])

Students with attendance percentage greater than 90:
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

In [ ]:
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

In [ ]:
top_student = df.loc[df['total_score'].idxmax()]
print("\nTop Student based on total score:")
print(f"Name: {top_student['name']}\nDepartment: {top_student['department']}\nTotal Score: {top_student['total_score']}")

Top Student based on total score:
Name: Ananya Das
Department: Computer Science
Total Score: 371

In [ ]:
import pandas as pd

# 1. Students with high attendance (greater than 90%)
high_attendance_students = df[df['attendance_percentage'] > 90]
print("Students with attendance percentage greater than 90:")
print(high_attendance_students[['name', 'department', 'attendance_percentage']])

# 2. Calculate total score for each student
df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

# 3. Find and print the top student based on total score
top_student = df.loc[df['total_score'].idxmax()]
print("\nTop Student based on total score:")
print(f"Name: {top_student['name']}\nDepartment: {top_student['department']}\nSum of all Marks: {top_student['total_score']}")
print(f"Individual Marks:\n  Math: {top_student['math_score']}\n  Science: {top_student['science_score']}\n  English: {top_student['english_score']}\n  Programming: {top_student['programming_score']}")

Students with attendance percentage greater than 90:
              name        department  attendance_percentage
0     Aarav Sharma  Computer Science                     92
3      Sneha Reddy        Mechanical                     95
7      Divya Singh  Computer Science                     96
9       Ananya Das  Computer Science                     98
13   Kavya Nambiar        Mechanical                     91
15    Ritu Agarwal       Electronics                     93
17  Swati Kulkarni  Computer Science                     94
21     Tanvi Mehta  Computer Science                     97
24       Amit Bose  Computer Science                     91
29  Akanksha Yadav  Computer Science                     95

Top Student based on total score:
Name: Ananya Das
Department: Computer Science
Sum of all Marks: 371
Individual Marks:
  Math: 95
  Science: 89
  English: 90
  Programming: 97

In [ ]:
department_avg_scores = df.groupby('department')[['math_score', 'science_score', 'english_score', 'programming_score']].mean().round(2)
print("Department-wise Average Scores:")
print(department_avg_scores)

Department-wise Average Scores:
                  math_score  science_score  english_score  programming_score
department
Civil                  63.40          66.60          65.20              40.60
Computer Science       85.62          84.46          80.85              89.23
Electronics            71.00          74.17          70.83              61.50
Mechanical             71.00          76.50          70.50              49.33

In [ ]:
department_total_avg_score = department_avg_scores[['math_score', 'science_score', 'english_score', 'programming_score']].sum(axis=1).round(2)
print("\nDepartment-wise Average of Sum of Scores:")
print(department_total_avg_score)

Department-wise Average of Sum of Scores:
department
Civil               235.80
Computer Science    340.16
Electronics         277.50
Mechanical          267.33
dtype: float64

In [ ]:
# Ensure 'total_score' is calculated (if not already)
if 'total_score' not in df.columns:
    df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

# Sort by total_score in descending order and get the top 5
top_5_students = df.sort_values(by='total_score', ascending=False).head(5)

print("\nTop 5 Students by Total Marks:")
print(top_5_students[['name', 'department', 'total_score']])

Top 5 Students by Total Marks:
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356

In [ ]:
# Find the student with the maximum total score among the top 5 (which is the overall top student)
overall_max_student = top_5_students.loc[top_5_students['total_score'].idxmax()]

print("\nOverall Top Student (from the top 5 list):")
print(f"Name: {overall_max_student['name']}")
print(f"Department: {overall_max_student['department']}")
print(f"Sum of all Marks: {overall_max_student['total_score']}")
print(f"Individual Marks:\n  Math: {overall_max_student['math_score']}\n  Science: {overall_max_student['science_score']}\n  English: {overall_max_student['english_score']}\n  Programming: {overall_max_student['programming_score']}")

Overall Top Student (from the top 5 list):
Name: Ananya Das
Department: Computer Science
Sum of all Marks: 371
Individual Marks:
  Math: 95
  Science: 89
  English: 90
  Programming: 97

In [ ]:
# Ensure 'total_score' is calculated (if not already)
# This column was likely created earlier, but we ensure its presence
if 'total_score' not in df.columns:
    df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

department_avg_total_score = df.groupby('department')['total_score'].mean().round(2)
print("\nDepartment-wise Average of Total Scores (simplified):")
print(department_avg_total_score)

Department-wise Average of Total Scores (simplified):
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:

department_total_avg_score = department_avg_scores[['math_score', 'science_score', 'english_score', 'programming_score']].sum(axis=1).round(2)
print("\nDepartment-wise Average of Sum of Scores:")
print(department_total_avg_score)

Department-wise Average of Sum of Scores:
department
Civil               235.80
Computer Science    340.16
Electronics         277.50
Mechanical          267.33
dtype: float64

In [ ]:


department_avg_total_score = df.groupby('department')['total_score'].mean().round(2)
print("\nDepartment-wise Average of Total Scores (simplified):")
print(department_avg_total_score)

Department-wise Average of Total Scores (simplified):
department
Civil               235.80
Computer Science    340.15
Electronics         277.50
Mechanical          267.33
Name: total_score, dtype: float64

In [ ]:
df_sorted = df.sort_values(by='total_score', ascending=False)

In [ ]:
display(df_sorted)

,student_id,name,age,gender,department,semester,math_score,science_score,english_score,programming_score,attendance_percentage,city,admission_year,total_score
9,1010,Ananya Das,19,Female,Computer Science,2,95,89,90,97,98,Kolkata,2023,371
21,1022,Tanvi Mehta,19,Female,Computer Science,2,93,90,88,96,97,Surat,2023,367
29,1030,Akanksha Yadav,19,Female,Computer Science,2,91,93,87,94,95,Agra,2023,365
4,1005,Arjun Nair,19,Male,Computer Science,2,92,88,81,95,90,Kochi,2023,356
7,1008,Divya Singh,19,Female,Computer Science,2,88,91,84,93,96,Lucknow,2023,356
17,1018,Swati Kulkarni,19,Female,Computer Science,2,90,87,85,92,94,Nagpur,2023,354
24,1025,Amit Bose,19,Male,Computer Science,2,86,82,79,89,91,Kolkata,2023,336
12,1013,Suresh Rao,21,Male,Computer Science,2,83,86,77,88,88,Mysore,2023,334
19,1020,Nisha Kapoor,19,Female,Computer Science,2,79,84,81,83,89,Chandigarh,2023,327
0,1001,Aarav Sharma,19,Male,Computer Science,2,85,78,72,91,92,Mumbai,2023,326
26,1027,Gaurav Shukla,21,Male,Computer Science,2,84,79,75,87,87,Lucknow,2023,325
15,1016,Ritu Agarwal,20,Female,Electronics,2,87,83,86,69,93,Agra,2023,325
1,1002,Priya Patel,20,Female,Computer Science,2,76,82,88,79,87,Ahmedabad,2023,325
10,1011,Vikram Iyer,20,Male,Electronics,2,80,75,68,72,83,Chennai,2023,295
23,1024,Preeti Saxena,20,Female,Mechanical,2,77,81,76,53,86,Kanpur,2023,287
25,1026,Rekha Nair,20,Female,Electronics,2,72,77,73,63,82,Kochi,2023,285
13,1014,Kavya Nambiar,20,Female,Mechanical,2,74,78,82,51,91,Thrissur,2023,285
14,1015,Ajay Tiwari,19,Male,Computer Science,2,71,69,64,76,75,Bhopal,2023,280
3,1004,Sneha Reddy,20,Female,Mechanical,2,70,80,75,48,95,Hyderabad,2023,273
28,1029,Nitin Jain,20,Male,Mechanical,2,75,76,70,50,84,Indore,2023,271
11,1012,Pooja Gupta,19,Female,Civil,2,67,72,79,44,80,Jaipur,2023,262
20,1021,Harish Pillai,20,Male,Electronics,2,64,70,67,58,74,Thiruvananthapuram,2023,259
2,1003,Rohit Verma,19,Male,Electronics,2,65,74,61,55,78,Delhi,2023,255
18,1019,Deepak Chauhan,20,Male,Mechanical,2,68,73,62,49,77,Dehradun,2023,252
6,1007,Kiran Kumar,21,Male,Civil,2,73,69,65,40,85,Bangalore,2023,247
5,1006,Meera Joshi,20,Female,Electronics,2,58,66,70,52,72,Pune,2023,246
8,1009,Rahul Mishra,20,Male,Mechanical,2,62,71,58,45,68,Varanasi,2023,236
27,1028,Sunita Pillai,19,Female,Civil,2,60,65,68,39,73,Thiruvananthapuram,2023,232
22,1023,Sanjay Dubey,21,Male,Civil,2,61,66,59,42,70,Allahabad,2023,228
16,1017,Manoj Pandey,21,Male,Civil,2,56,61,55,38,65,Patna,2023,210

pyth no desc,asec=false=desc

## **Mini Project:Student data explorer**
**Objective:**

Create a Student Perfomance Explorer using Python
and pandas to analyse student data and generate a detailed report

**Dataset columns**:


name ,gender, dept ,math_score ,programming_score, attendance percentage,
total_score



**Task to perform:**


**1.Display project title**

print a formatted title with separator lines

**2.Dataset overview:**
  
   Display:
-total number of students
-total number of columns
--number of unique departments

**3.Department-wise analysis:**
Display the count of students in each department


**4.Score analysis:**
find and display:
-Highest math score
-Lowest math score
-Average math score
-Average programmming score
-Average attendance percentage


**5.Gender-wise analysis:**
Calculate and display average total score grouped by gender

**6.Top performers**
Display the top 5 students based on total_score
show:
-student Name
-Dept
-Total score


**7.Attendance analysis**
Find the students whose attendance is below 75%
display:
-name
-dept
-attendance  percentage
If all students have attendance above 75%
print a suitable message

**
Concepts to use
-pandas,Data frame, groupby(),value_counts(),mean(),max(),min(),sort_values(),
iterrows()**

mini project:student data explorer
student performance using python nd pandas,to analyse student data nd generate a detailed report,
database columns
name,gender,dept

In [14]:
import pandas as pd

# ==================================================
#         STUDENT PERFORMANCE EXPLORER
# ==================================================

print("==================================================")
print("         STUDENT PERFORMANCE EXPLORER")
print("==================================================")

# Loading Dataset
df = pd.read_csv("student_performance (1).csv")

print("Dataset loaded successfully")

print("--------------------------------------------------")

# ==================================================
#               1. DATASET OVERVIEW
# ==================================================

print("==================================================")
print("               DATASET OVERVIEW")
print("==================================================")

# Total number of students
total_students = df.shape[0]
print("Total Number of Students :", total_students)

# Total number of columns
total_columns = df.shape[1]
print("Total Number of Columns :", total_columns)

# Number of unique departments
unique_departments = df["department"].nunique()
print("Number of Unique Departments :", unique_departments)

print("--------------------------------------------------")

# ==================================================
#           2. DEPARTMENT-WISE ANALYSIS
# ==================================================

print("==================================================")
print("         DEPARTMENT-WISE ANALYSIS")
print("==================================================")

department_count = df["department"].value_counts()

print("Student Count in Each Department")
print(department_count)

print("--------------------------------------------------")

# ==================================================
#                 3. SCORE ANALYSIS
# ==================================================

print("==================================================")
print("               SCORE ANALYSIS")
print("==================================================")

# Highest math score
highest_math = df["math_score"].max()
print("Highest Math Score :", highest_math)

# Lowest math score
lowest_math = df["math_score"].min()
print("Lowest Math Score :", lowest_math)

# Average math score
average_math = df["math_score"].mean()
print("Average Math Score :", round(average_math,2))

# Average programming score
average_programming = df["programming_score"].mean()
print("Average Programming Score :", round(average_programming,2))

# Average attendance percentage
average_attendance = df["attendance_percentage"].mean()
print("Average Attendance Percentage :", round(average_attendance,2))

print("--------------------------------------------------")

# ==================================================
#             4. GENDER-WISE ANALYSIS
# ==================================================

print("==================================================")
print("            GENDER-WISE ANALYSIS")
print("==================================================")

# First, calculate total_score if it's not already present
if 'total_score' not in df.columns:
    df['total_score'] = df['math_score'] + df['science_score'] + df['english_score'] + df['programming_score']

gender_average = df.groupby("gender")["total_score"].mean()

print("Average Total Score Based on Gender")
print(round(gender_average,2))

print("--------------------------------------------------")

# ==================================================
#                 5. TOP PERFORMERS
# ==================================================

print("==================================================")
print("                TOP PERFORMERS")
print("==================================================")

top_students = df.sort_values(by="total_score", ascending=False)

top_5 = top_students.head(5)

print("Top 5 Students Based on Total Score")
print(top_5[["name","department","total_score"]])

print("--------------------------------------------------")

# ==================================================
#               6. ATTENDANCE ANALYSIS
# ==================================================

print("==================================================")
print("             ATTENDANCE ANALYSIS")
print("==================================================")

low_attendance = df[df["attendance_percentage"] < 75]

if low_attendance.empty:
    print("All students have attendance above 75%")
else:
    print("Students with Attendance Below 75%")
    print(low_attendance[["name","department","attendance_percentage"]])

==================================================
         STUDENT PERFORMANCE EXPLORER
==================================================
Dataset loaded successfully
--------------------------------------------------
==================================================
               DATASET OVERVIEW
==================================================
Total Number of Students : 30
Total Number of Columns : 13
Number of Unique Departments : 4
--------------------------------------------------
==================================================
         DEPARTMENT-WISE ANALYSIS
==================================================
Student Count in Each Department
department
Computer Science    13
Electronics          6
Mechanical           6
Civil                5
Name: count, dtype: int64
--------------------------------------------------
==================================================
               SCORE ANALYSIS
==================================================
Highest Math Score : 95
Lowest Math Score : 56
Average Math Score : 76.07
Average Programming Score : 67.6
Average Attendance Percentage : 84.5
--------------------------------------------------
==================================================
            GENDER-WISE ANALYSIS
==================================================
Average Total Score Based on Gender
gender
Female    310.67
Male      280.67
Name: total_score, dtype: float64
--------------------------------------------------
==================================================
                TOP PERFORMERS
==================================================
Top 5 Students Based on Total Score
              name        department  total_score
9       Ananya Das  Computer Science          371
21     Tanvi Mehta  Computer Science          367
29  Akanksha Yadav  Computer Science          365
4       Arjun Nair  Computer Science          356
7      Divya Singh  Computer Science          356
--------------------------------------------------
==================================================
             ATTENDANCE ANALYSIS
==================================================
Students with Attendance Below 75%
             name   department  attendance_percentage
5     Meera Joshi  Electronics                     72
8    Rahul Mishra   Mechanical                     68
16   Manoj Pandey        Civil                     65
20  Harish Pillai  Electronics                     74
22   Sanjay Dubey        Civil                     70
27  Sunita Pillai        Civil                     73